services:
  mysql-teasy:
    image: mysql:8.0
    container_name: mysql-teasy
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rapida-root-2026
      MYSQL_DATABASE: teasy
      MYSQL_USER: teasy
      MYSQL_PASSWORD: le-sang-app-2026
    volumes:
      - teasy_mysql_data:/var/lib/mysql
      # Décommente si tu veux injecter un dump SQL au premier démarrage
      # - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin-teasy:
    image: phpmyadmin:5.2.3-apache
    container_name: phpmyadmin-teasy
    restart: unless-stopped
    depends_on:
      - mysql-teasy
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-teasy
      PMA_PORT: 3306

volumes:
  teasy_mysql_data:
